SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59AA1A6D59}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{6A2F5CAA8EC2D2BC}" {
     m_sEntityPrefab "{B116CCA3642E7552}Prefabs/Attachments/Core/ShawBrainPouch.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A2F5CAABE5BAC4A}" {
       m_eItemType EQUIPMENT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A2E857216427879}" {
     m_sEntityPrefab "{E43924D345A0A0BD}Prefabs/Characters/HeadGear/Helmet_PASGT_01/SFHELMETAOR1.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A2E8572164278C5}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 1
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A2F5CAA5C99AD4C}" {
     m_sEntityPrefab "{AF457DB4423C4107}Prefabs/Characters/HeadGear/Helmet_PASGT_01/SF_HELMETAOR1.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A2F5CAA5C99D2E3}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 1
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A2E85723A668F09}" {
     m_sEntityPrefab "{F054E1A17D68D6F3}Prefabs/Characters/HeadGear/Helmet_PASGT_01/SFHELMETMCB.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A2E85723A668F4C}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 1
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A2E8572007617A4}" {
     m_sEntityPrefab "{E1F107716548EAF1}Prefabs/Characters/HeadGear/Helmet_PASGT_01/SFHELMETGRN.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A2E8572007617EE}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 1
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A2E85723CB4245A}" {
     m_sEntityPrefab "{0EFA61D445A76173}Prefabs/Characters/HeadGear/Helmet_PASGT_01/SFHELMETMULTICAM.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A2E85723CB4249C}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 1
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A2E857230D25DF9}" {
     m_sEntityPrefab "{369046752B1D3674}Prefabs/Characters/HeadGear/Helmet_PASGT_01/SFHELMETRG.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A2E857230D25E3F}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 1
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A2E857234AA6F7F}" {
     m_sEntityPrefab "{6B48CC8B6CB07712}Prefabs/Characters/HeadGear/Helmet_PASGT_01/SFHELMETTAN.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A2E857234AA6FC0}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 1
      }
     }
    }
   }
  }
 }
}